# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings
name: 柯蓝手绘工作室
markdown: redcarpet
paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
pygments: true

title: lygblog
description: Stylish Jekyll Theme
author:
  name: lygblog
  email: luoyonggang@gmail.com
  github: lygstate
  twitter: asd123
  pinterest: asd123
  linkedin: asd123
  bio: Yonggang Luo's 研究积累

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html


encoding: UTF-8

# All links will be namespaced by BASE_PATH if defined.
# Links in your website should always be prefixed with {{ site.BASE_PATH }}
# Do not put a "/" at the end of the url.
#
# CNAME (http://yourcustomdomain.com)
#   DO NOT SET BASE_PATH JUST LEAVE IT BLANK 
#   (urls will be prefixed with "/" and work relatively)
#
# GitHub Pages (http://username.github.io)
#   DO NOT SET BASE_PATH JUST LEAVE IT BLANK 
#   (urls will be prefixed with "/" and work relatively)
#
# GitHub Project Pages (http://username.github.io/project-name)
#  A GitHub Project site exists in the `gh-pages` branch of one of your repositories.
#  REQUIRED! Set BASE_PATH to "http://username.github.io/project-name"
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]